package modelo;
// Generated 09-jul-2016 7:50:35 by Hibernate Tools 4.3.1



/**
 * Ejemplo generated by hbm2java
 */
public class Ejemplo  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;

    public Ejemplo() {
    }

    public Ejemplo(String nombre, String descripcion) {
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


